package com.radiotv.tvremote.core

enum class RemoteKey {
    POWER, MUTE, INPUT, VOLUME_UP, VOLUME_DOWN, CHANNEL_UP, CHANNEL_DOWN,
    UP, DOWN, LEFT, RIGHT, OK, BACK, HOME, MENU,
    PLAY, PAUSE, STOP, REWIND, FAST_FORWARD, SEARCH,
    DIGIT_0, DIGIT_1, DIGIT_2, DIGIT_3, DIGIT_4,
    DIGIT_5, DIGIT_6, DIGIT_7, DIGIT_8, DIGIT_9
}
